Package: generic/all/custom-util-skel  * Add admin-friendly options to all 'profile-{fix,use}-*' utilities

diff --git a/generic/all/custom-util-skel/usr/bin/profile-use-nssdb b/generic/all/custom-util-skel/usr/bin/profile-use-nssdb
--- a/generic/all/custom-util-skel/usr/bin/profile-use-nssdb
+++ b/generic/all/custom-util-skel/usr/bin/profile-use-nssdb
@@ -11,13 +11,50 @@ SYNOPSIS:
   certificate(s) and point relevant applications to it.
   <certificate> must be specified as:
     <name>:<path>:<trust> (as used by 'certutil' -n ... -i ... -t ...)
+
+OPTIONS:
+  --home <absolute-directory-path>
+    Specify home directory absolute path
+    (default: ${HOME})
+
+  --dry-run
+    Only show potentially mis-permissioned (existing) files
+
+  --verbose
+    Output additonal debug/informational messages.
 EOF
+
+# Arguments
+MY_HOME="${HOME}"
+DRYRUN=
+VERBOSE=
+while [ -n "${1}" ]; do
+  case "${1}" in
+    '--home')
+      [ -z "${2}" ] && echo "ERROR: Missing option argument (${1})" >&2 && exit 1
+      shift; MY_HOME="${1}"
+      ;;
+    '--dry-run')
+      DRYRUN='yes'
+      ;;
+    '--verbose')
+      VERBOSE='yes'
+      ;;
+    -*)
+      echo "ERROR: Invalid option (${1})" >&2 && exit 1
+      ;;
+    *)
+      break
+  esac
+  shift
+done
 
 
 ## Create/update the shared NSS database
-echo "DEBUG: ${0##*/} BEGIN"
-NSSDBDIR="${HOME}/.pki/nssdb"
+[ -n "${VERBOSE}" ] && echo "DEBUG: ${0##*/} BEGIN"
+NSSDBDIR="${MY_HOME}/.pki/nssdb"
 CERTUTIL="certutil -d sql:${NSSDBDIR}"
+[ -n "${VERBOSE}" ] && echo "DEBUG: Checking NSS database directory (${NSSDBDIR})"
 
 # Check the NSS database directory
 if [ ! -d "${NSSDBDIR}" -o ! -e "${NSSDBDIR}/cert9.db" -o ! -e "${NSSDBDIR}/key4.db" -o ! -e "${NSSDBDIR}/pkcs11.txt" ]; then
@@ -34,30 +71,46 @@ while [ -n "${1}" ]; do
   cert_name="${cert%%:*}"; cert="${cert#*:}"
   cert_file="${cert%%:*}"; cert="${cert#*:}"
   cert_trust="${cert%%:*}"
+  [ -n "${VERBOSE}" ] && echo "DEBUG: Adding certificate to NSS database (${cert_name}:${cert_file}:${cert_trust})"
+  [ -n "${DRYRUN}" ] && echo "DRY-RUN: NOT adding certificate to NSS database (${cert_name}:${cert_file}:${cert_trust})" && continue
   ${CERTUTIL} -L -n ${cert_name} >/dev/null 2>&1 || ${CERTUTIL} -A -n "${cert_name}" -i "${cert_file}" -t "${cert_trust}"
   [ $? -ne 0 ] && echo "WARNING: Failed to add certificate (${cert})" >&2
 done
 
 # Update/check application profiles
 for profile in \
-  $(find '.thunderbird/' -maxdepth 2 -type f -name 'prefs.js') \
-  $(find '.mozilla/firefox/' -maxdepth 3 -type f -name 'prefs.js')
+  $(find "${MY_HOME}/.thunderbird/" -maxdepth 2 -type f -name 'prefs.js') \
+  $(find "${MY_HOME}/.mozilla/firefox/" -maxdepth 3 -type f -name 'prefs.js')
 do
   profile="$(dirname "${profile}")"
+  [ -n "${VERBOSE}" ] && echo "DEBUG: Checking NSS database in user profile (${profile})"
   if [ -e "${profile}/cert8.db" -o -e "${profile}/key3.db" ]; then
-    echo "INFO: Cleaning deprecated NSS database from profile (${profile})"
-    rm -f "${profile}/cert8.db" "${profile}/key3.db"
+    if [ -n "${DRYRUN}" ]; then
+      echo "DRY-RUN: NOT cleaning deprecated NSS database from user profile (${profile})"
+    else
+      echo "INFO: Cleaning deprecated NSS database from user profile (${profile})"
+      rm -f "${profile}/cert8.db" "${profile}/key3.db"
+    fi
   fi
   if [ ! -h "${profile}/cert9.db" -o ! -h "${profile}/key4.db" ]; then
-    echo "INFO: Symlinking NSS database (${profile})"
-    [ -e "${profile}/cert9.db" -a "${profile}/key4.db" ] && ${CERTUTIL} --merge --source-dir "${profile}"
-    rm -f "${profile}/cert9.db" "${profile}/key4.db"
-    ln -s "${NSSDBDIR}/cert9.db" "${profile}/cert9.db"
-    ln -s "${NSSDBDIR}/key4.db" "${profile}/key4.db"
+    if [ -n "${DRYRUN}" ]; then
+      echo "DRY-RUN: NOT symlinking NSS database in user profile (${profile})"
+    else
+      echo "INFO: Symlinking NSS database in user profile (${profile})"
+      [ -e "${profile}/cert9.db" -a "${profile}/key4.db" ] && ${CERTUTIL} --merge --source-dir "${profile}"
+      rm -f "${profile}/cert9.db" "${profile}/key4.db"
+      ln -s "${NSSDBDIR}/cert9.db" "${profile}/cert9.db"
+      ln -s "${NSSDBDIR}/key4.db" "${profile}/key4.db"
+    fi
   fi
   if [ ! -h "${profile}/pkcs11.txt" ]; then
-    rm -f "${profile}/pkcs11.txt"
-    ln -s "${NSSDBDIR}/pkcs11.txt" "${profile}/pkcs11.txt"
+    if [ -n "${DRYRUN}" ]; then
+      echo "DRY-RUN: NOT symlinking PKCS#11 configuration in user profile (${profile})"
+    else
+      echo "INFO: Symlinking PKCS#11 configuration in user profile (${profile})"
+      rm -f "${profile}/pkcs11.txt"
+      ln -s "${NSSDBDIR}/pkcs11.txt" "${profile}/pkcs11.txt"
+    fi
   fi
 done
 
@@ -66,6 +119,6 @@ export NSS_DEFAULT_DB_TYPE='sql'
 
 
 ## Done
-echo "DEBUG: ${0##*/} END"
+[ -n "${VERBOSE}" ] && echo "DEBUG: ${0##*/} END"
 exit 0
 
diff --git a/generic/all/custom-util-skel/usr/bin/profile-use-tmpdir b/generic/all/custom-util-skel/usr/bin/profile-use-tmpdir
--- a/generic/all/custom-util-skel/usr/bin/profile-use-tmpdir
+++ b/generic/all/custom-util-skel/usr/bin/profile-use-tmpdir
@@ -4,24 +4,77 @@
 
 ## Usage
 [ "${1##*-}" == 'help' ] && cat << EOF && exit 1
-USAGE: ${0##*/}
+USAGE: ${0##*/} [options]
 
 SYNOPSIS:
   Create local user-dedicated temporary directory and relocate all
   non-critical resources (web cache, thumbnails cache, etc.) to
   that directory.
+
+OPTIONS:
+  --home <absolute-directory-path>
+    Specify home directory absolute path
+    (default: ${HOME})
+
+  --user <username>
+    Specify alternate username (for permissions setting)
+    (default: ${USER})
+
+  --tmp <absolute-directory-path>
+    Specify temporary (local) directory absolute path
+    (default: /local/scratch or /tmp)
+
+  --dry-run
+    Only show potentially mis-permissioned (existing) files
+
+  --verbose
+    Output additonal debug/informational messages.
 EOF
+
+# Arguments
+MY_HOME="${HOME}"
+MY_USER="${USER}"
+TMPROOT=
+DRYRUN=
+VERBOSE=
+while [ -n "${1}" ]; do
+  case "${1}" in
+    '--home')
+      [ -z "${2}" ] && echo "ERROR: Missing option argument (${1})" >&2 && exit 1
+      shift; MY_HOME="${1}"
+      ;;
+    '--user')
+      [ -z "${2}" ] && echo "ERROR: Missing option argument (${1})" >&2 && exit 1
+      shift; MY_USER="${1}"
+      ;;
+    '--tmp')
+      [ -z "${2}" ] && echo "ERROR: Missing option argument (${1})" >&2 && exit 1
+      shift; TMPROOT="${1}"
+      ;;
+    '--dry-run')
+      DRYRUN='yes'
+      ;;
+    '--verbose')
+      VERBOSE='yes'
+      ;;
+    *)
+      echo "ERROR: Invalid option (${1})" >&2 && exit 1
+  esac
+  shift
+done
 
 
 ## Create the local temporary directory
-echo "DEBUG: ${0##*/} BEGIN"
+[ -n "${VERBOSE}" ] && echo "DEBUG: ${0##*/} BEGIN"
 
 # Define/check the parent (root) directory
-[ -e '/local/scratch' ] && TMPROOT='/local/scratch' || TMPROOT='/tmp'
+if [ -z "${TMPROOT}" ]; then
+  [ -e '/local/scratch' ] && TMPROOT='/local/scratch' || TMPROOT='/tmp'
+fi
 [ ! -d "${TMPROOT}" ] && echo "ERROR: Invalid path; not a directory (${TMPROOT})" >&2 && exit 1
 
 # Define/create/check the user directory
-TMPDIR="${TMPROOT}/${USER}"
+TMPDIR="${TMPROOT}/${MY_USER}"
 [ ! -e "${TMPDIR}" ] && mkdir "${TMPDIR}"
 [ ! -d "${TMPDIR}" ] && echo "ERROR: Failed to create directory (${TMPDIR})" >&2 && exit 1
 [ ! -w "${TMPDIR}" ] && echo "ERROR: Non-writable directory (${TMPDIR})" >&2 && exit 1
@@ -31,7 +84,7 @@ export TMPROOT
 export TMPDIR
 
 # Set proper ownership and permissions
-chown "${USER}" "${TMPDIR}"
+chown "${MY_USER}" "${TMPDIR}"
 chmod go= "${TMPDIR}"
 
 
@@ -41,14 +94,16 @@ function _relocate_resource {  # <home-relative-directory>:<type=dir|file>
   resource="${1%:*}"
   resource_type="${1#*:}"
   [ "${resource}" == "${resource_type}" ] && echo "ERROR: Invalid resource syntax (${resource})" >&2 && return 1
-  resource_home_path="${HOME}/${resource}"
+  resource_home_path="${MY_HOME}/${resource}"
   resource_home_dir="$(dirname "${resource_home_path}")"
   resource_tmp_path="${TMPDIR}/${resource}"
   resource_tmp_dir="$(dirname "${resource_tmp_path}")"
+  [ -n "${VERBOSE}" ] && echo "DEBUG: Checking resource (${resource_home_path})"
 
   # Initial check
   [ -h "${resource_home_path}" -a -e "${resource_home_path}" ] && return 0
-  echo "INFO: Relocating resource... (${resource_home_path})"
+  [ -n "${DRYRUN}" ] && echo "DRY-RUN: NOT relocating resource (${resource_home_path})" && return 0
+  echo "INFO: Relocating resource (${resource_home_path})"
   
   # Check (parent) directory
   # ... home
@@ -104,8 +159,8 @@ function _relocate_resource {  # <home-relative-directory>:<type=dir|file>
 
 
 ## Relocate resources
-cd "${HOME}"
-[ $? -ne 0 ] && echo "ERROR: Failed to swicth to home directory (${HOME})" >&2 && exit 1
+cd "${MY_HOME}"
+[ $? -ne 0 ] && echo "ERROR: Failed to swicth to home directory (${MY_HOME})" >&2 && exit 1
 IFS=$'\n'
 
 # Easy ones
@@ -183,6 +238,6 @@ done
 
 
 ## Done
-echo "DEBUG: ${0##*/} END"
+[ -n "${VERBOSE}" ] && echo "DEBUG: ${0##*/} END"
 exit 0
 
