Package: generic/all/custom-util-blockdev  * Consolidated 'blockdev-*' scripts

diff --git a/generic/all/custom-util-blockdev/usr/sbin/blockdev-rereadpt b/generic/all/custom-util-blockdev/usr/sbin/blockdev-rereadpt
--- a/generic/all/custom-util-blockdev/usr/sbin/blockdev-rereadpt
+++ b/generic/all/custom-util-blockdev/usr/sbin/blockdev-rereadpt
@@ -3,18 +3,18 @@
 
 ## Usage
 [ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
-USAGE: ${0##*/} <lun#>
+USAGE: ${0##*/} <device>
 
-HINT: echo 1 > /sys/class/scsi_device/0:0:0:<lun#>/device/rescan
+HINT: blockdev --rereadpt <device>
 EOF
 
 # Arguments
-LUNID="${1}"
+DEVICE="${1##*/}"
 
 
 ## Command
-SYSDEV="/sys/class/scsi_device/0:0:0:${LUNID}"
-[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid device/LUN (${SYSDEV})" >&2 && exit 1
+SYSDEV="/sys/block/${DEVICE}"
+[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid block device (${SYSDEV})" >&2 && exit 1
 echo 'CRITICAL: Make sure to umount all partitions on the device!'
 for dev in ${SYSDEV}/device/block/sd*; do
   echo " > device: ${dev##*/}"
@@ -24,9 +24,8 @@ for dev in ${SYSDEV}/device/block/sd*; do
 done
 echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
 read
-echo 1 > ${SYSDEV}/device/rescan
+blockdev --rereadpt "/dev/${DEVICE}"
 sleep 3
-for blockdev in ${SYSDEV}/device/block/sd*; do
-  parted /dev/${blockdev##*/} -- unit mb print
-done
+ls -al /dev/disk/by-uuid | fgrep "${DEVICE}"
+ls -al /dev/disk/by-label | fgrep "${DEVICE}"
 
diff --git a/generic/all/custom-util-blockdev/usr/sbin/blockdev-rescan b/generic/all/custom-util-blockdev/usr/sbin/blockdev-rescan
--- a/generic/all/custom-util-blockdev/usr/sbin/blockdev-rescan
+++ b/generic/all/custom-util-blockdev/usr/sbin/blockdev-rescan
@@ -3,18 +3,18 @@
 
 ## Usage
 [ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
-USAGE: ${0##*/} <lun#>
+USAGE: ${0##*/} <device>
 
-HINT: echo 1 > /sys/class/scsi_device/0:0:0:<lun#>/device/rescan
+HINT: echo 1 > /sys/block/<device>/device/rescan
 EOF
 
 # Arguments
-LUNID="${1}"
+DEVICE="${1##*/}"
 
 
 ## Command
-SYSDEV="/sys/class/scsi_device/0:0:0:${LUNID}"
-[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid device/LUN (${SYSDEV})" >&2 && exit 1
+SYSDEV="/sys/block/${DEVICE}"
+[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid block device (${SYSDEV})" >&2 && exit 1
 echo 'CRITICAL: Make sure to umount all partitions on the device!'
 for dev in ${SYSDEV}/device/block/sd*; do
   echo " > device: ${dev##*/}"
diff --git a/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete b/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
--- a/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
+++ b/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
@@ -1,18 +1,22 @@
 #!/bin/bash
 ## CUSTOM-UTIL: File automatically created/updated [custom-util-blockdev]
 
-# Usage
+## Usage
 [ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
 USAGE: ${0##*/} <lun#>
 
 HINT: echo 1 > /sys/class/scsi_device/0:0:0:<lun#>/device/delete
 EOF
 
-# Command
-LUNDEV="/sys/class/scsi_device/0:0:0:${1}"
-[ ! -e "${LUNDEV}" ] && echo "ERROR: Invalid device/LUN (${LUNDEV})" >&2 && exit 1
+# Arguments
+LUNID="${1}"
+
+
+## Command
+SYSDEV="/sys/class/scsi_device/0:0:0:${LUNID}"
+[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid device/LUN (${SYSDEV})" >&2 && exit 1
 echo 'CRITICAL: Make sure to umount all partitions on the device!'
-for dev in ${LUNDEV}/device/block/sd*; do
+for dev in ${SYSDEV}/device/block/sd*; do
   echo " > device: ${dev##*/}"
   for part in ${dev}/sd*; do
     echo " > partition: /dev/${part##*/}"
@@ -20,4 +24,5 @@ for dev in ${LUNDEV}/device/block/sd*; do
 done
 echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
 read
-echo 1 > ${LUNDEV}/device/delete
+echo 1 > ${SYSDEV}/device/delete
+
