Package: generic/all/custom-util-blockdev  * Consolidated 'scsi{host,dev}-*' scripts

diff --git a/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete b/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
--- a/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
+++ b/generic/all/custom-util-blockdev/usr/sbin/scsidev-delete
@@ -3,20 +3,20 @@
 
 ## Usage
 [ $# -lt 1 -o "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
-USAGE: ${0##*/} <lun#>
+USAGE: ${0##*/} <scsi-device>
 
-HINT: echo 1 > /sys/class/scsi_device/0:0:0:<lun#>/device/delete
+HINT: echo 1 > /sys/class/scsi_device/<scsi-device>/device/delete
 EOF
 
 # Arguments
-LUNID="${1}"
+SCSI_DEVICE="${1}"
 
 
 ## Command
-SYSDEV="/sys/class/scsi_device/0:0:0:${LUNID}"
-[ ! -e "${SYSDEV}" ] && echo "ERROR: Invalid device/LUN (${SYSDEV})" >&2 && exit 1
+SCSI_CLASS="/sys/class/scsi_device/${SCSI_DEVICE}"
+[ ! -e "${SCSI_CLASS}" ] && echo "ERROR: Invalid SCSI device (${SCSI_DEVICE}) <-> class (${SCSI_CLASS})" >&2 && exit 1
 echo 'CRITICAL: Make sure to umount all partitions on the device!'
-for dev in ${SYSDEV}/device/block/sd*; do
+for dev in ${SCSI_CLASS}/device/block/sd*; do
   echo " > device: ${dev##*/}"
   for part in ${dev}/sd*; do
     echo " > partition: /dev/${part##*/}"
@@ -24,5 +24,5 @@ for dev in ${SYSDEV}/device/block/sd*; do
 done
 echo 'PRESS <ENTER> TO CONTINUE OR <CTRL+C> TO ABORT...'
 read
-echo 1 > ${SYSDEV}/device/delete
+echo 1 > ${SCSI_CLASS}/device/delete
 
diff --git a/generic/all/custom-util-blockdev/usr/sbin/scsihost-refresh b/generic/all/custom-util-blockdev/usr/sbin/scsihost-refresh
--- a/generic/all/custom-util-blockdev/usr/sbin/scsihost-refresh
+++ b/generic/all/custom-util-blockdev/usr/sbin/scsihost-refresh
@@ -3,15 +3,26 @@
 
 ## Usage
 [ "${1##*-}" == 'help' ] && cat << EOF >&2 && exit 1
-USAGE: ${0##*/}
+USAGE: ${0##*/} [<scsi-host>=host0]
 
-HINT: echo '- - -' > /sys/class/scsi_host/host0/scan
+HINT: echo '- - -' > /sys/class/scsi_host/<scsi-host>/scan
 EOF
 
+# Arguments
+[ -n "${1}" ] && SCSI_HOST="${1}" || SCSI_HOST='host0'
+
+# Checks
+SCSI_CLASS="/sys/class/scsi_host/${SCSI_HOST}"
+[ ! -e "${SCSI_CLASS}" ] && echo "ERROR: Invalid SCSI host (${SCSI_HOST}) <-> class (${SCSI_CLASS})" >&2 && exit 1
+SCSI_PATH="$(readlink "${SCSI_CLASS}")"
+[ -z "${SCSI_PATH}" ] && echo "ERROR: Invalid class path (${SCSI_CLASS})" >&2 && exit 1
 
 ## Command
+echo 'INFO: Triggering SCSI host refresh...'
+echo "  ${SCSI_CLASS} ->"
+echo "  ${SCSI_PATH}"
 echo '- - -' > /sys/class/scsi_host/host0/scan
-echo 'Waiting for SCSI host refresh...'
 sleep 3
-ls -al /dev/disk/by-id/
+echo 'INFO: Attached SCSI devices'
+ls -1 /dev/disk/by-path/*scsi*
 
