Package: generic/all/custom-conf-ssh  * Make sure all host keys are custom-conf'ed

diff --git a/generic/all/custom-conf-ssh/debian/postinst b/generic/all/custom-conf-ssh/debian/postinst
--- a/generic/all/custom-conf-ssh/debian/postinst
+++ b/generic/all/custom-conf-ssh/debian/postinst
@@ -151,22 +151,27 @@ gcfg.sed "s|%{CUSTOM_CONF_SSH_LISTEN_IPV4}|${CUSTOM_CONF_SSH_LISTEN_IPV4}|g;s|%{
 gcfg.sed "s|%{CUSTOM_CONF_SSH_TCPKEEPALIVE}|${CUSTOM_CONF_SSH_TCPKEEPALIVE}|g;s|%{CUSTOM_CONF_SSH_HASHKNOWNHOSTS}|${CUSTOM_CONF_SSH_HASHKNOWNHOSTS}|g;s|%NL;|\n|g" /etc/ssh/ssh_config
 
 # Additional actions
-sshkey_comment="$(hostname -f) (generated $(date +"%Y-%m-%d") with OpenSSL $(dpkg -l | grep 'ii\s*libssl' | awk '{print $3}' | sort -V | head -n 1))"
-if [ ! -e /etc/ssh/ssh_host_ed25519_key.pub ]; then
-  echo "WARNING[${PKGNAME}]: The ED25519 key does not exist"
-  echo ': creating new ED25519 key...'
+openssl_version="$(dpkg -l | grep 'ii\s*libssl' | awk '{print $3}' | sort -V | head -n 1)"
+hostkey_version='1'
+sshkey_generator="generated by custom-conf-ssh[v${hostkey_version}]"
+sshkey_comment="$(hostname -f) (${sshkey_generator} $(date +"%Y-%m-%d") with OpenSSL ${openssl_version})"
+if ! grep -qwF "${sshkey_generator}" /etc/ssh/ssh_host_ed25519_key.pub; then
+  echo "WARNING[${PKGNAME}]: Missing/invalid ED25519 host key"
+  echo ': creating new ED25519 host key...'
+  rm -f /etc/ssh/ssh_host_ed25519_key /etc/ssh/ssh_host_ed25519_key.pub
   /usr/bin/ssh-keygen -q -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key -C "${sshkey_comment}"
   /usr/bin/ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub
 fi
-#if [ ! -e /etc/ssh/ssh_host_ecdsa_key.pub ]; then
-#  echo "WARNING[${PKGNAME}]: The ECDSA key does not exist"
-#  echo ': creating new ECDSA key...'
-#  /usr/bin/ssh-keygen -q -b 256 -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key -C "${sshkey_comment}"
-#  /usr/bin/ssh-keygen -lf /etc/ssh/ssh_host_ecdsa_key.pub
-#fi
-if [ ! -e /etc/ssh/ssh_host_rsa_key.pub -o "$(ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub | cut -d' ' -f1)" == '2048' ]; then
-  echo "WARNING[${PKGNAME}]: The RSA key does not exist or its length does not match security policies"
-  echo ': creating new RSA key...'
+if ! grep -qwF "${sshkey_generator}" /etc/ssh/ssh_host_ecdsa_key.pub; then
+  echo "WARNING[${PKGNAME}]: Missing/invalid ECDSA host key"
+  echo ': creating new ECDSA host key...'
+  rm -f /etc/ssh/ssh_host_ecdsa_key /etc/ssh/ssh_host_ecdsa_key.pub
+  /usr/bin/ssh-keygen -q -b 256 -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key -C "${sshkey_comment}"
+  /usr/bin/ssh-keygen -lf /etc/ssh/ssh_host_ecdsa_key.pub
+fi
+if ! grep -qwF "${sshkey_generator}" /etc/ssh/ssh_host_rsa_key.pub || [ "$(ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub | cut -d' ' -f1)" == '2048' ]; then
+  echo "WARNING[${PKGNAME}]: Missing/invalid RSA host key"
+  echo ': creating new RSA host key...'
   rm -f /etc/ssh/ssh_host_rsa_key /etc/ssh/ssh_host_rsa_key.pub
   /usr/bin/ssh-keygen -q -b $[2049+$RANDOM%511] -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key -C "${sshkey_comment}"
   /usr/bin/ssh-keygen -lf /etc/ssh/ssh_host_rsa_key.pub
