Package: generic/all/custom-util-ha  * Added support (compatibility) for Lenovo branding in IBM/Lenovo FlexSystem    chassis management modules (CMM) STONITH device (ibmfx)

diff --git a/generic/all/custom-util-ha/usr/lib/stonith/plugins/external/ibmfx b/generic/all/custom-util-ha/usr/lib/stonith/plugins/external/ibmfx
--- a/generic/all/custom-util-ha/usr/lib/stonith/plugins/external/ibmfx
+++ b/generic/all/custom-util-ha/usr/lib/stonith/plugins/external/ibmfx
@@ -2,8 +2,8 @@
 ## CUSTOM-UTIL: File automatically created/updated [custom-util-ha]
 
 ###############################################################################
-# External STONITH module for IBM FlexSystem (SNMPv3)
-# 2014.07.08 <http://cedric.dufour.name>
+# External STONITH module for IBM/Lenovo FlexSystem (SNMPv3)
+# 2017.02.17 <http://cedric.dufour.name>
 ###############################################################################
 
 # Command-line arguments
@@ -38,7 +38,8 @@ ARG_HOSTNAME="$2"
 
 # OIDs
 OID_IBMFX_SIG='.1.3.6.1.2.1.1.1.0'
-OID_IBMFX_SIG_CHECK='IBM Flex Chassis Management Module'
+OID_IBMFX_SIG_CHECK_IBM='IBM Flex Chassis Management Module'
+OID_IBMFX_SIG_CHECK_LENOVO='Lenovo Flex Chassis Management Module'
 OID_IBMFX_NAME_PREFIX='.1.3.6.1.4.1.2.3.51.2.22.1.6.1.1.6'
 OID_IBMFX_STATE_PREFIX='.1.3.6.1.4.1.2.3.51.2.22.1.6.1.1.4'
 OID_IBMFX_POWER_PREFIX='.1.3.6.1.4.1.2.3.51.2.22.1.6.1.1.7'
@@ -64,7 +65,7 @@ function _devchk() {
   [ -z "$(which snmpset)" ] && echo "ERROR: Missing SNMP binary (snmpset)" >&2 && return 1
   sig="$(snmpget -m '' -t 5 -r 15 -Ov -Oq ${mgmt_address} ${OID_IBMFX_SIG} | sed 's|"||g')"
   [ $? -ne 0 ] && echo "ERROR: Failed to retrieve SNMP device signature" >&2 && return 1
-  [ "${sig,,}" != "${OID_IBMFX_SIG_CHECK,,}" ] && echo "ERROR: Invalid device signature (${sig})" >&2 && return 1
+  [ "${sig,,}" != "${OID_IBMFX_SIG_CHECK_IBM,,}" -a "${sig,,}" != "${OID_IBMFX_SIG_CHECK_LENOVO,,}" ] && echo "ERROR: Invalid device signature (${sig})" >&2 && return 1
   return 0
 }
 
@@ -197,22 +198,22 @@ getconfignames)
   ;;
 
 getinfo-devid)
-  echo "IBM FlexSystem STONITH device"
+  echo "IBM/Lenovo FlexSystem STONITH device"
   exit 0
   ;;
 
 getinfo-devname)
-  echo "IBM FlexSystem STONITH device (${snmp_conf_path})"
+  echo "IBM/Lenovo FlexSystem STONITH device (${snmp_conf_path})"
   exit 0
   ;;
 
 getinfo-devdescr)
-  echo "IBM FlexSystem's STONITH device via SNMPv3"
+  echo "IBM/Lenovo FlexSystem's STONITH device via SNMPv3"
   exit 0
   ;;
 
 getinfo-devurl)
-  echo 'http://www.ibm.com/'
+  echo 'http://www.lenovo.com/'
   exit 0
   ;;
 
@@ -226,7 +227,7 @@ getinfo-xml)
 Management Address (or Hostname)
 </shortdesc>
 <longdesc lang="en">
-The IP address or hostname for the IBM FlexSystem (CMM).
+The IP address or hostname for the IBM/Lenovo FlexSystem (CMM).
 </longdesc>
 </parameter>
 
@@ -237,7 +238,7 @@ SNMP Configuration Directory Path
 </shortdesc>
 <longdesc lang="en">
 The path to the directory containing the 'snmp.conf' configuration file to
-access the IBM FlexSystem (CMM).
+access the IBM/Lenovo FlexSystem (CMM).
 See 'man snmp_config' and 'man snmp.conf' for details.
 </longdesc>
 </parameter>
